### ISSUE TITLE
bug in click interaction?

### ISSUE THREAD

**Issue by jakopako** [jakopako/goskyr#224]
```yml
    interaction:
      type: click
      selector: body > div.page > div > div.row.row-stretch-row-content-no-padding.row-css-2 > div > div > div > div > div.events > a
```

with this config the load-more button is not being clicked...
