### ISSUE TITLE
Slow Pagination

### ISSUE THREAD

**Issue by alucab** [jakopako/goskyr#245]
I have this simple scraper

```
scrapers:
  - name: discontinued
    renderJs: true
    url: https://www.hikvision.com/en/products/discontinued-products
    item: "li.layout4-content-wrapper"
    fields:
      - name: "title"
        location:
          selector: "h3.h3-seo"
      - name: status
        can_be_empty: true
        type: text
        location:
        - selector: .tag-eol
      - name: desc
        type: text
        location:
          - selector: h4.h4-seo
      - name: link
        type: url
        location:
          - selector: ".btn-details-link"
    paginator:
      location:
        selector: "#layout-pagination-wrapper > ul > li:nth-child(9) > span"
      max_pages: 3
```
  
It works correctly but it is dramatically slow. It takes at least 40 secs for every page and i don't understand why, as the pagination as the data is preloaded in the page and the refresh from the browser extremely quick

**Comment by jakopako** [comment]
Thanks for bringing this up. You're right, when setting `renderJs: true`, the scraper is pretty slow. This part of the code is not yet very optimized and there are a bunch of hardcoded timers ( e.g. here: https://github.com/jakopako/goskyr/blob/main/fetch/fetcher.go#L73 ) to make sure the site has actually loaded. I'll look into this in more detail as soon as I have time. Feel free to make some improvements yourself and make a pull request if you have some ideas :)

**Comment by alucab** [comment]
I will certainly give a look, but i have veeeeery limited experience with golang so i take it more as a learning opportunity than the possibility to concretely contribute in the short term.

Thanks for being so reactive !

**Comment by jakopako** [comment]
Sure, no worries! 

Yeah, you might be totally right, it could very well be that the reinstantiation is the thing that takes so much time.

**Comment by jakopako** [comment]
I released a new version, 0.5.8, that should be a little better speed-wise. It reuses the same browser instance for multiple requests, and you can change the default (which is now 2) page load wait time with the key `page_load_wait_sec`. So your config could look something like:

```
scrapers:
  - name: discontinued
    renderJs: true
    page_load_wait_sec: 1
    url: https://www.hikvision.com/en/products/discontinued-products
...
```

It's still not very fast but it should already be better than before. Hope this helps!
