### ISSUE TITLE
click interaction not working

### ISSUE THREAD

**Issue by jakopako** [jakopako/goskyr#255]
```
  - name: X-TRA
    url: "https://www.x-tra.ch/en/program/concerts/"
    item: ".events .tile li"
    renderJs: true
    interaction:
      type: click
      selector: div.events > a.more
      count: 1
    fields:
      - name: "location"
        value: "X-TRA"
      - name: "city"
        value: "Zurich"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: "https://www.x-tra.ch/en/agenda/concerts/"
      - name: "title"
        location:
          selector: ".text h2"
      - name: "url"
        type: "url"
        location:
          selector: "a"
      - name: "comment"
        can_be_empty: true
        on_subpage: "url"
        location:
          selector: ".left .content p"
          max_length: 200
      - name: "date"
        type: "date"
        on_subpage: "url"
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: ".caption .text h3"
            layout: ["Mon 02.01.06"]
          - covers:
              time: true
            location:
              selector: ".time li strong"
              node_index: 1
            transform:
              - type: regex-replace
                regex: "p\\.m\\."
                replace: pm
            layout: ["3.04 pm "]
        date_location: "Europe/Berlin"
        date_language: "en_US"
```
