### ISSUE TITLE
Add type 'list' field

### ISSUE THREAD

**Issue by jakopako** [jakopako/goskyr#326]
This field type should allow you to include a field which is a list of strings. 
As an example this could be a list of genres for a concert. 

Still have to think this through but from a configuration perspective we probably only need to support setting this new type (no other list specific configuration parameters). Maybe some of the configuration parameters need to be well defined in the context of a list type.

**Comment by castaway** [comment]
I think this should be a setting on field, which makes any field type return a list instead of a string. (Though this will make life more interesting for tools reading the output..)

**Comment by jakopako** [comment]
I agree, it makes more sense to eventually support lists of any type (currently `url`, `text` or `date`).

**Comment by jakopako** [comment]
I thought I'd add some examples here to make this a bit more clear. Basically the idea is to eventually allow having a list type of every existing type, `list(text)`, `list(url)`, `list(date)` (could also define it in a more go-like way, `[]text`), while also still allowing for the "base types" and all their corresponding options that exist now.

Let's start with type `list(text)` which is probably the easiest. The following cases are the ones I can currently think of.

**CASE 1**

html:
```html
<span>
  <span class="">Jazz</span>
  <span class="">Experimental</span>
  <span class="">Spoken Word</span>
</span>
```

output:
```json
{
  "genres": ["Jazz", "Experimental", "Spoken Word"]
}
```

config:
```yaml
fields:
  - name: "genres"
    type: "list(text)" # or "[]text" or ...
    location:
      - selector: "span > span"
        all_nodes: true
```

**CASE 2**

html:
```html
<div>
  <h2>Main Artist</h2>
  <div class="additionalArtist">
    <h4>Additional Artist</h4>
  </div>
</div>
```

output:
```json
{
  "artists": ["Main Artist", "Additional Artist"]
}
```

config:
```yaml
fields:
  - name: "artists"
    type: "list(text)"
    location:
      - selector: "div > h2"
      - selector: "div > div > h4>"
```

**CASE 3**

html:
```html
<span>Jazz, Experimental, Spoken Word</span>
```

output:
```json
{
  "genres": ["Jazz", "Experimental", "Spoken Word"]
}
```

config:
```yaml
fields:
  - name: "genres"
    type: "list(text)"
    location:
      - selector: "span"
        separator: ", "
```

Maybe we also want to allow for combinations of above cases such as

**CASE 4**

html:
```html
<div>
  <h2>Main Artist</h2>
  <div class="additionalArtists">
    <h4>Additional Artist 1, Additional Artist 2</h4>
  </div>
</div>
```

output:
```json
{
  "artists": ["Main Artist", "Additional Artist 1", "Additional Artist 2"]
}
```

config:
```yaml
fields:
  - name: "artists"
    type: "list(text)"
    location:
      - selector: "div > h2"
      - selector: "div > div > h4>"
        separator: ", "
```
